### ISSUE TITLE
Error: Execution failed

### ISSUE THREAD

**Issue by RundesBalli** [vikenemesh/ExtendedBenis#12]
Das Userscript schmeißt seit heute folgenden Error:
![grafik](https://user-images.githubusercontent.com/46271553/100659740-54065200-3351-11eb-878e-9484433435a7.png)

**Comment by 0xAdriian** [comment]
![image](https://user-images.githubusercontent.com/20760589/100792227-9fd0fe00-341a-11eb-8228-e35a1784ec86.png)
Maybe: @holzmaster

**Comment by vikenemesh** [comment]
Ist repariert!

**Comment by RundesBalli** [comment]
Besten Dank. Funktioniert!
