### ISSUE TITLE
Colors of Bar

### ISSUE THREAD

**Issue by pr0nopoly** [vikenemesh/ExtendedBenis#7]
Maybe we should change the colors from green/FTB to Orange/Grey to match up with the rest of the site.

**Comment by vikenemesh** [comment]
Wait, I have a pull-request I need to merge. Maybe this will be a non-issue then.

**Comment by pr0nopoly** [comment]
IMO, the colors of the bar should match the color of the active voting buttons to stay consistent with the site design:
![minus](https://cloud.githubusercontent.com/assets/8378791/6350160/adbcfa08-bc31-11e4-9821-db76ae6b1bab.png)
![plus](https://cloud.githubusercontent.com/assets/8378791/6350161/adbf2b5c-bc31-11e4-9796-8a8ec4b7607d.png)

Meaning the orange stays for something good, since the whole site is using it (in a positive way, unlike the grey for negative things).

But that's just my two cents.

**Comment by vikenemesh** [comment]
I'll think about it.

**Comment by vikenemesh** [comment]
No one else complained and I'm fine with the way it is.
