### ISSUE TITLE
Videos lassen sich nicht mehr vor/-zurückspulen

### ISSUE THREAD

**Issue by TheMcSebi** [vikenemesh/ExtendedBenis#9]
Seit dem Ton-Update (danke Gamb) vor ein paar Tagen lässt sich bei aktiviertem Userscript die blaue Suchleiste nicht mehr bedienen. Könnte mit der Umstellung von webm auf mp4 zusammenhängen. Alle anderen Userscripts verursachen keine Probleme.

**Comment by holzmaster** [comment]
Habe es mit dem PR #10 gefixt. Muss nur noch gemergt werden.

**Comment by vikenemesh** [comment]
Viel Dank holzmaster, ich schau mir das gleich an!

**Comment by vikenemesh** [comment]
Yes. Kann so bleiben.
